Update action.yaml (#625)

diff --git a/.github/actions/deploy_kind/action.yaml b/.github/actions/deploy_kind/action.yaml
--- a/.github/actions/deploy_kind/action.yaml
+++ b/.github/actions/deploy_kind/action.yaml
@@ -103,3 +103,14 @@ runs:
       mage gen:hostfileTraefik | sudo tee -a /etc/hosts > /dev/null
       echo "Updated Hostfile entries!"
       mage gen:orchCa deploy:orchCa
+
+  - name: Collect Pod Logs After Deploymnet
+    if: always()
+    shell: bash
+    run: |
+      echo "Start collecting Pod Logs"
+      ./ci/collect_pod_logs.sh  
+      echo "Application Summary:"
+      cat pod_logs/summary-applications.txt || echo "summary-applications.txt not found"  
+      echo "Pod Summary:"
+      cat pod_logs/summary-pods.txt || echo "summary-pods.txt not found"
